# Generated by Django 5.2.8 on 2025-12-04 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('idRegistre', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=100)),
                ('control_number', models.CharField(max_length=50)),
                ('heartbeat', models.IntegerField(blank=True, null=True)),
                ('pas', models.IntegerField(blank=True, null=True)),
                ('pad', models.IntegerField(blank=True, null=True)),
                ('breathbeat', models.IntegerField(blank=True, null=True)),
                ('corporalTemp', models.FloatField(blank=True, null=True)),
                ('pain', models.IntegerField(blank=True, null=True)),
                ('ocular', models.CharField(blank=True, max_length=20, null=True)),
                ('verbal', models.CharField(blank=True, max_length=20, null=True)),
                ('motor_response', models.CharField(blank=True, max_length=20, null=True)),
                ('skin_colour', models.CharField(blank=True, max_length=20, null=True)),
                ('trugidity', models.CharField(blank=True, max_length=20, null=True)),
                ('cardiac_output', models.IntegerField(blank=True, null=True)),
                ('cvp', models.CharField(blank=True, max_length=20, null=True)),
                ('perfution', models.FloatField(blank=True, null=True)),
                ('_map', models.IntegerField(blank=True, null=True)),
                ('hemoglobin', models.CharField(blank=True, max_length=20, null=True)),
                ('hemotocrit', models.IntegerField(blank=True, null=True)),
                ('pupilary', models.CharField(blank=True, max_length=20, null=True)),
                ('muscle_tone', models.CharField(blank=True, max_length=20, null=True)),
                ('posture', models.CharField(blank=True, max_length=20, null=True)),
                ('bmi', models.FloatField(blank=True, max_length=5, null=True)),
                ('urinary_flow', models.IntegerField(blank=True, max_length=3, null=True)),
                ('arterial_oxigen', models.IntegerField(blank=True, max_length=4, null=True)),
                ('cranial_pressure', models.IntegerField(blank=True, max_length=4, null=True)),
                ('fk_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
